services:
    dmzx.hangman.controller:
        class: dmzx\hangman\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    dmzx.hangman.listener:
        class: dmzx\hangman\event\listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
